### ISSUE TITLE
bug: session_auth_axum example crashes on page refresh

### ISSUE THREAD

**Issue by PlGGS** [leptos-rs/leptos#1097]
The session_auth_axum example crashes if you refresh your browser on any page other then the root of the app. This can be quickly replicated by refreshing either the login or signup page.

I originally thought the issue might have to do with being logged out or logged in as a guest, but it doesn't matter if you're logged into the db or not. You can verify this by clicking the settings button while logged in to navigate to /settings and then refreshing.

```
2023-05-25T09:45:07.835Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.837Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.840Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.842Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.844Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.847Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.849Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.851Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.853Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
2023-05-25T09:45:07.855Z INFO  [leptos_axum] generate_response;
thread '<unnamed>' panicked at 'could not get stored value', /home/blake/source/repos/leptos/leptos_server/src/action.rs:121:16
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/blake/source/repos/leptos/integrations/axum/src/lib.rs:714:44
``` 

I tried wrapping all of the TodoApp routes with ErrorBoundaries like the one that's wrapped around the main Todos component by default in the example, but that doesn't fix the issue.

I confirmed that the issue has to do with the Login/Signup/Logout components taking an Action parameter by removing the parameter and corresponding ActionForm component from the Signup component.

The following version of the Signup component doesn't crash, but it also doesn't work for obvious reasons:

```
#[component]
pub fn Signup(
    cx: Scope,
    // action: Action<Signup, Result<(), ServerFnError>>,
) -> impl IntoView {
    view! {
        cx,
        // <ActionForm action=action>
            <h1>"Sign Up"</h1>
            <label>
                "User ID:"
                <input type="text" placeholder="User ID" maxlength="32" name="username" class="auth-input" />
            </label>
            <br/>
            <label>
                "Password:"
                <input type="password" placeholder="Password" name="password" class="auth-input" />
            </label>
            <br/>
            <label>
                "Confirm Password:"
                <input type="password" placeholder="Password again" name="password_confirmation" class="auth-input" />
            </label>
            <br/>
            <label>
                "Remember me?"
                <input type="checkbox" name="remember" class="auth-input" />
            </label>

            <br/>
            <button type="submit" class="button">"Sign Up"</button>
        // </ActionForm>
    }
}
```

```
<Route path="signup" view=move |cx| view! {
    cx,
    <Signup/>
}/>
```

**Comment by gbj** [comment]
Thanks, yeah there's definitely something weird going on here that suggests a deeper bug somewhere. I'll take a look at it, thanks for the report.

**Comment by ViSaturn** [comment]
I've been experiencing exactly this error on actix aswell, with the latest stable version of leptos 0.4.6:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
```
I made a minimal reproducible version here: https://github.com/ViSaturn/leptos-actix-action-form-bug
