### ISSUE TITLE
ActionForm breaks on Actix after page refresh if action is passed by parent component

### ISSUE THREAD

**Issue by ViSaturn** [leptos-rs/leptos#1483]
**Describe the bug**
With leptos 0.4.6, ActionForm's break on page refresh if you are on actix and the action was created and passed to the component by a parent component, rather than being created by the component itself. The error takes a few reloads to happen though (on my computer, exactly 3).

The issue is very similar to #1097, the only difference I see is that the error happens on Actix rather than on Axum.

This is the error you get in the terminal after you reproduce the issue:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
thread 'actix-rt|system:0|arbiter:1' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
```

<details>
<summary>And with `RUST_BACKTRACE=1`:</summary>
<br>
thread 'actix-rt|system:0|arbiter:0' panicked at 'could not get stored value', /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:16
stack backtrace:
   0: rust_begin_unwind
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/option.rs:1952:5
   5: core::option::Option<T>::expect
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/option.rs:898:21
   6: leptos_reactive::stored_value::StoredValue<T>::with_value
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/stored_value.rs:130:9
   7: leptos_server::action::Action<I,O>::url
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.4.6/src/action.rs:138:9
   8: leptos_router::components::form::ActionForm::__ActionForm
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/form.rs:377:41
   9: leptos_router::components::form::ActionForm::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/form.rs:351:1
  10: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:44
  11: leptos_reactive::runtime::RuntimeId::untrack::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:498:32
  12: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
  14: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
  15: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
  16: leptos_reactive::runtime::RuntimeId::untrack
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:488:9
  17: leptos_reactive::scope::Scope::untrack_with_diagnostics
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:218:9
  18: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:13
  19: leptos_reactive::runtime::RuntimeId::run_scope_undisposed
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:464:10
  20: leptos_reactive::scope::Scope::run_child_scope
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:159:13
  21: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:274:26
  22: <Func as leptos::ComponentConstructor<P>>::construct
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:327:9
  23: leptos::component_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:302:5
  24: leptos_start::app::HomePage::__HomePage::{{closure}}
             at ./src/app.rs:47:5
  25: leptos_dom::components::fragment::Fragment::lazy
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components/fragment.rs:73:47
  26: leptos_start::app::HomePage::__HomePage
             at ./src/app.rs:47:5
  27: leptos_start::app::HomePage::{{closure}}
             at ./src/app.rs:41:1
  28: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:44
  29: leptos_reactive::runtime::RuntimeId::untrack::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:498:32
  30: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
  31: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
  32: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
  33: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
  34: leptos_reactive::runtime::RuntimeId::untrack
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:488:9
  35: leptos_reactive::scope::Scope::untrack_with_diagnostics
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:218:9
  36: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:13
  37: leptos_reactive::runtime::RuntimeId::run_scope_undisposed
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:464:10
  38: leptos_reactive::scope::Scope::run_child_scope
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:159:13
  39: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:274:26
  40: <Func as leptos::ComponentConstructor<P>>::construct
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:327:9
  41: leptos::component_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:302:5
  42: leptos_start::app::App::__App::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/app.rs:24:51
  43: leptos_router::components::route::Route::__Route::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/route.rs:70:27
  44: leptos_router::components::route::RouteContext::new::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/route.rs:219:49
  45: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2021:9
  46: leptos_router::components::route::RouteContext::outlet
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/route.rs:303:9
  47: leptos_router::components::routes::root_route::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:436:46
  48: core::option::Option<T>::map
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/option.rs:1075:29
  49: leptos_router::components::routes::root_route::{{closure}}::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:435:29
  50: leptos_reactive::runtime::RuntimeId::run_scope_undisposed
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:464:10
  51: leptos_reactive::scope::Scope::run_child_scope
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:159:13
  52: leptos_router::components::routes::root_route::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:427:46
  53: leptos_reactive::memo::forward_ref_to::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:215:9
  54: leptos_reactive::signal::<impl leptos_reactive::node::NodeId>::try_with_no_subscription
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/signal.rs:1996:12
  55: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::try_with::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:421:13
  56: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
  58: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
  59: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
  60: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::try_with
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:419:9
  61: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::with
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:393:15
  62: leptos_router::components::routes::root_route::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:416:13
  63: <leptos_reactive::memo::MemoState<T,F> as leptos_reactive::effect::AnyComputation>::run
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:508:29
  64: leptos_reactive::runtime::Runtime::update::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:130:25
  65: leptos_reactive::runtime::Runtime::with_observer
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:179:17
  66: leptos_reactive::runtime::Runtime::update
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:126:21
  67: leptos_reactive::runtime::Runtime::update_if_necessary
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:103:13
  68: leptos_reactive::signal::<impl leptos_reactive::node::NodeId>::try_with_no_subscription_inner
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/signal.rs:1974:9
  69: leptos_reactive::signal::<impl leptos_reactive::node::NodeId>::try_with_no_subscription
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/signal.rs:1990:21
  70: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::try_with::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:421:13
  71: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
  72: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
  73: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
  74: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
  75: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::try_with
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:419:9
  76: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalWith<T>>::with
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:393:15
  77: <leptos_reactive::memo::Memo<T> as leptos_reactive::signal::SignalGet<T>>::get
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/memo.rs:354:9
  78: <leptos_reactive::signal_wrappers_read::Signal<T> as leptos_reactive::signal::SignalGet<T>>::get
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/signal_wrappers_read.rs:292:37
  79: leptos_router::components::routes::Routes::__Routes::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:60:59
  80: <leptos_dom::components::dyn_child::DynChild<CF,N> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components/dyn_child.rs:398:30
  81: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2021:9
  82: <leptos_dom::components::dyn_child::DynChild<CF,N> as leptos_dom::IntoView>::into_view::create_dyn_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components/dyn_child.rs:383:33
  83: <leptos_dom::components::dyn_child::DynChild<CF,N> as leptos_dom::IntoView>::into_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components/dyn_child.rs:395:25
  84: leptos_router::components::routes::Routes::__Routes
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:60:5
  85: leptos_router::components::routes::Routes::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/routes.rs:27:1
  86: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:44
  87: leptos_reactive::runtime::RuntimeId::untrack::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:498:32
  88: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
  89: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
  90: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
  91: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
  92: leptos_reactive::runtime::RuntimeId::untrack
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:488:9
  93: leptos_reactive::scope::Scope::untrack_with_diagnostics
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:218:9
  94: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:13
  95: leptos_reactive::runtime::RuntimeId::run_scope_undisposed
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:464:10
  96: leptos_reactive::scope::Scope::run_child_scope
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:159:13
  97: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:274:26
  98: <Func as leptos::ComponentConstructor<P>>::construct
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:327:9
  99: leptos::component_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.4.6/src/lib.rs:302:5
 100: leptos_start::app::App::__App::{{closure}}::{{closure}}::{{closure}}
             at ./src/app.rs:12:5
 101: leptos_dom::components::fragment::Fragment::lazy
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components/fragment.rs:73:47
 102: leptos_start::app::App::__App::{{closure}}::{{closure}}
             at ./src/app.rs:12:5
 103: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/core/src/ops/function.rs:250:5
 104: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/alloc/src/boxed.rs:2007:9
 105: leptos_router::components::router::Router::__Router
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/router.rs:43:5
 106: leptos_router::components::router::Router::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.4.6/src/components/router.rs:18:1
 107: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:44
 108: leptos_reactive::runtime::RuntimeId::untrack::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:498:32
 109: leptos_reactive::runtime::with_runtime::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:384:41
 110: std::thread::local::LocalKey<T>::try_with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:270:16
 111: std::thread::local::LocalKey<T>::with
             at /rustc/32303b219d4dffa447aa606bc11c7a648f44a862/library/std/src/thread/local.rs:246:9
 112: leptos_reactive::runtime::with_runtime
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:380:13
 113: leptos_reactive::runtime::RuntimeId::untrack
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:488:9
 114: leptos_reactive::scope::Scope::untrack_with_diagnostics
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:218:9
 115: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:275:13
 116: leptos_reactive::runtime::RuntimeId::run_scope_undisposed
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/runtime.rs:464:10
 117: leptos_reactive::scope::Scope::run_child_scope
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.4.6/src/scope.rs:159:13
 118: <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view
             at /home/ambiverse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.6/src/components.rs:274:26
</details>

**Leptos Dependencies**
```toml
leptos = { version = "0.4", features = ["nightly"] }
leptos_meta = { version = "0.4", features = ["nightly"] }
leptos_actix = { version = "0.4", optional = true }
leptos_router = { version = "0.4", features = ["nightly"] }
```

**To Reproduce**
1. Clone https://github.com/ViSaturn/leptos-actix-action-form-bug
2. Run `cargo leptos watch`
3. Visit the resulting site locally.
4. Refresh the page a few times, on my computer, 3 times exactly on every run, to see the error.
5. See the error back in the terminal.

**Expected behavior**
Expected the page to still function after refresh.

**Screenshots**
Not necessary.

**Additional context**
I built the project using `cargo-leptos`.

**Comment by ViSaturn** [comment]
Using a context worked, thanks, I couldn't tell whether #1397 was related to the issue so I ignored it.
