### ISSUE TITLE
Common build failures 

### ISSUE THREAD

**Issue by martinfrances107** [leptos-rs/leptos#1575]
there have been a spate of build failures over the last few days

All seen to have a common failure point 

> Documenting bumpalo v3.13.0

I am just pulling out one example of of the panic so we can reason about it..

For the moment here is my only comment, as I see more I will add to the issue.

nightly is failing....

The github workflow has been improved greatly, with lots of extra stages ... 
The visibility, the extra checking .. is maybe telling us ,, maybe to file an issue in a downstream crate.

I don't have an opinion yet...

```
Documenting bumpalo v3.13.0
thread 'rustc' panicked at src/librustdoc/passes/lint/redundant_explicit_links.rs:107:41:
byte index 1 is not a char boundary; it is inside '…' (bytes 0..3) of `…alloc_with(|| x)`
stack backtrace:
   0:     0x7f5efa75b0fc - std::backtrace_rs::backtrace::libunwind::trace::h05dcd57d35354e09
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5efa75b0fc - std::backtrace_rs::backtrace::trace_unsynchronized::h760cef756255b640
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5efa75b0fc - std::sys_common::backtrace::_print_fmt::h96ee9c0f36e8a7ef
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f5efa75b0fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h79540d81556adb82
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5efa7c13bc - core::fmt::rt::Argument::fmt::h29465cb5b004890a
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/core/src/fmt/rt.rs:138:9
   5:     0x7f5efa7c13bc - core::fmt::write::hdd9d58a2540bd20b
                               at /rustc/c469197b19d53a6c45378568f73c00986b20a5a5/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f5efa74db2e - std::io::Write::write_fmt::h198a947e286d709f
note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `bumpalo`

Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustdoc --edition=2021 --crate-type lib --crate-name bumpalo /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bumpalo-3.13.0/src/lib.rs --cap-lints allow -o /home/runner/work/leptos/leptos/leptos_macro/example/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=02a943d1362b8fab -L dependency=/home/runner/work/leptos/leptos/leptos_macro/example/target/debug/deps --crate-version 3.13.0` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
Error: Process completed with exit code 1.
```

**Comment by gbj** [comment]
My understanding is that this is an ICE on latest Rust nightly while compiling bumpalo at some point during our workflow.

(I haven't taken any other action on it other than running CI locally on whatever version I've got installed, which passes.)

**Comment by gbj** [comment]
This seems to have resolved itself somewhere between the compiler and bumpalo, and is no longer causing errors in CI.
