### ISSUE TITLE
Panic when adding Title or Meta element in my app

### ISSUE THREAD

**Issue by dfeyer** [leptos-rs/leptos#1954]
**Describe the bug**
When adding Title, Meta or Stylesheet, the app panik, with the following backtrace:

```
thread 'main' panicked at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9:
cannot call wasm-bindgen imported functions on non-wasm targets
stack backtrace:
   0:     0x55fdbf54b4cc - std::backtrace_rs::backtrace::libunwind::trace::h0c647d84ac50d453
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fdbf54b4cc - std::backtrace_rs::backtrace::trace_unsynchronized::h7f227a939c586a6d
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fdbf54b4cc - std::sys_common::backtrace::_print_fmt::h5510ec3e6f55d730
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55fdbf54b4cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h003091095e62af49
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fdbf576a30 - core::fmt::rt::Argument::fmt::hae3463b15867b29b
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/fmt/rt.rs:142:9
   5:     0x55fdbf576a30 - core::fmt::write::h2ba083205f2f4c36
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/fmt/mod.rs:1117:17
   6:     0x55fdbf548cef - std::io::Write::write_fmt::hc4c0547f4c0c916f
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/io/mod.rs:1762:15
   7:     0x55fdbf54b2b4 - std::sys_common::backtrace::_print::h82ce630649ce1017
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fdbf54b2b4 - std::sys_common::backtrace::print::h8f4ebac7fe2c9a89
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fdbf54ca67 - std::panicking::default_hook::{{closure}}::h0226f8d320e0f17e
  10:     0x55fdbf54c7cf - std::panicking::default_hook::h5f6196165d4c15e9
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:292:9
  11:     0x55fdbf54cee8 - std::panicking::rust_panic_with_hook::h052bb4d563e7ed88
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:731:13
  12:     0x55fdbef2cf68 - std::panicking::begin_panic::{{closure}}::ha9bc4b99e7e9049d
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:639:9
  13:     0x55fdbef2c7da - std::sys_common::backtrace::__rust_end_short_backtrace::hc079c11988b1aa85
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55fdbef2ced7 - std::panicking::begin_panic::h42f0d156f3ba67ff
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:638:12
  15:     0x55fdbef2bf1d - js_sys::global::get_global_object::Global::get_self::__wbg_self_1ff1d729e9aae938::hb6ad6b51318ae626
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9
  16:     0x55fdbef2be89 - js_sys::global::get_global_object::Global::get_self::hb875868ac8327718
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9
  17:     0x55fdbef2b593 - js_sys::global::get_global_object::h99bd659d101c4c22
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5866:29
  18:     0x55fdbef2bc96 - js_sys::global::GLOBAL::__init::h26e057ede6c27b64
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5825:43
  19:     0x55fdbef2bd2f - js_sys::global::GLOBAL::__getit::{{closure}}::he67767d2b288a9b7
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:99:25
  20:     0x55fdbef2cc65 - std::sys::common::thread_local::lazy::LazyKeyInner<T>::initialize::h1acd32c3a424d228
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/mod.rs:54:25
  21:     0x55fdbef2c821 - std::sys::common::thread_local::fast_local::Key<T>::try_initialize::h22132a1a94458258
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:190:27
  22:     0x55fdbef2c9fb - std::sys::common::thread_local::fast_local::Key<T>::get::h0980bd4c30f223b6
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:173:25
  23:     0x55fdbef2bcd7 - js_sys::global::GLOBAL::__getit::ha4814187d6947ec1
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:91:21
  24:     0x55fdbef2cd84 - std::thread::local::LocalKey<T>::try_with::h4819e6ee4ad7cdb7
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:269:32
  25:     0x55fdbef2cd2f - std::thread::local::LocalKey<T>::with::he755145d260f4486
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:246:9
  26:     0x55fdbef2b55e - js_sys::global::h16189f0c7059fbfc
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5827:12
  27:     0x55fdbef2b24a - web_sys::window::h9420da6c79f26864
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.64/src/lib.rs:31:5
  28:     0x55fdbef060bd - leptos_dom::DOCUMENT::__init::hf9ee8446e672733a
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.5.2/src/lib.rs:983:53
  29:     0x55fdbef061ef - leptos_dom::DOCUMENT::__getit::{{closure}}::h2b79b5f2b9c5f4fd
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:99:25
  30:     0x55fdbeedf0a5 - std::sys::common::thread_local::lazy::LazyKeyInner<T>::initialize::h378551eba596569a
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/mod.rs:54:25
  31:     0x55fdbef07e81 - std::sys::common::thread_local::fast_local::Key<T>::try_initialize::h40a2dca406fcca36
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:190:27
  32:     0x55fdbef081eb - std::sys::common::thread_local::fast_local::Key<T>::get::h23b34c69892afcab
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:173:25
  33:     0x55fdbef06197 - leptos_dom::DOCUMENT::__getit::h11bb545d98ea31ba
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys/common/thread_local/fast_local.rs:91:21
  34:     0x55fdbef25024 - std::thread::local::LocalKey<T>::try_with::h3d8429366c821f6e
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:269:32
  35:     0x55fdbef24eff - std::thread::local::LocalKey<T>::with::h675e640d990cd8e4
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:246:9
  36:     0x55fdbeef78ce - leptos_dom::document::h44c750b35a8954d5
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.5.2/src/lib.rs:999:5
  37:     0x55fdbeb76d1d - leptos_meta::MetaTagsContext::register::h356a3fdd3dc60ab0
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_meta-0.5.2/src/lib.rs:139:42
  38:     0x55fdbeb794c3 - leptos_meta::meta_tags::Meta::__Meta::hed869ff864d8ca0b
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_meta-0.5.2/src/meta_tags.rs:62:5
  39:     0x55fdbeb78d82 - leptos_meta::meta_tags::Meta::h3e8b9d8b87e048d8
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_meta-0.5.2/src/meta_tags.rs:24:1
  40:     0x55fdbe99997b - core::ops::function::Fn::call::hfdcda5a462612a88
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/ops/function.rs:79:5
  41:     0x55fdbe9e273b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1c3dab4eab2b1b3
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/ops/function.rs:284:13
  42:     0x55fdbe9e27ba - <Func as leptos::ComponentConstructor<P>>::construct::h2b9afe471e975ac8
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.5.2/src/lib.rs:352:9
  43:     0x55fdbe9b6fd7 - leptos::component_view::h18c180aed479c031
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.5.2/src/lib.rs:327:5
  44:     0x55fdbe99dba0 - ui_app::App::__App::{{closure}}::hc566b273e642173d
                               at /home/dfeyer/Projects/src/gitlab.ttree.ch/dfeyer/DialogHarvest/ui-app/src/lib.rs:14:5
  45:     0x55fdbe9afa5e - leptos_dom::components::fragment::Fragment::lazy::hc84a36eefa9e6bba
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.5.2/src/components/fragment.rs:75:47
  46:     0x55fdbe9afa5e - ui_app::App::__App::haa68058848949e98
                               at /home/dfeyer/Projects/src/gitlab.ttree.ch/dfeyer/DialogHarvest/ui-app/src/lib.rs:14:5
  47:     0x55fdbe99d984 - ui_app::App::{{closure}}::h645f94ac9d256b0b
                               at /home/dfeyer/Projects/src/gitlab.ttree.ch/dfeyer/DialogHarvest/ui-app/src/lib.rs:10:1
  48:     0x55fdbe997a20 - <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::h399c75fe95c8fe23
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.5.2/src/components.rs:281:49
  49:     0x55fdbe9e5571 - leptos_reactive::runtime::RuntimeId::untrack::{{closure}}::hc0e8352762df3012
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/runtime.rs:957:32
  50:     0x55fdbe9e2826 - leptos_reactive::runtime::with_runtime::{{closure}}::h20d0bb27653232b5
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/runtime.rs:696:39
  51:     0x55fdbe9b1ef8 - std::thread::local::LocalKey<T>::try_with::hd7aa8bc1eaa4ae73
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:270:16
  52:     0x55fdbe9b0514 - std::thread::local::LocalKey<T>::with::ha714675497a4a083
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/thread/local.rs:246:9
  53:     0x55fdbe988dfb - leptos_reactive::runtime::with_runtime::ha71a5e6af4f1d906
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/runtime.rs:696:16
  54:     0x55fdbe988dfb - leptos_reactive::runtime::RuntimeId::untrack::h36f1522c8e027ddd
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/runtime.rs:944:9
  55:     0x55fdbe988dfb - leptos_reactive::runtime::untrack_with_diagnostics::hf58f3f896ea05391
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.2/src/runtime.rs:1519:5
  56:     0x55fdbe988dfb - <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::h7972e0f85c2317a4
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.5.2/src/components.rs:281:21
  57:     0x55fdbe89b1c5 - leptos_router::extract_routes::generate_route_list_inner::hbb21e2e3e1196527
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_router-0.5.2/src/extract_routes.rs:126:9
  58:     0x55fdbe68906c - leptos_axum::generate_route_list_with_exclusions_and_ssg::h6350837af10e013a
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_axum-0.5.2/src/lib.rs:1339:9
  59:     0x55fdbe676986 - leptos_axum::generate_route_list::h87ea1e2f3fb6be3d
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_axum-0.5.2/src/lib.rs:1295:5
  60:     0x55fdbe7bf7d8 - ui_api::main::{{closure}}::hf5cf6649670b1eb0
                               at /home/dfeyer/Projects/src/gitlab.ttree.ch/dfeyer/DialogHarvest/ui-api/src/main.rs:40:18
  61:     0x55fdbe703934 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h6cbb861ee57b9d5d
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/park.rs:282:63
  62:     0x55fdbe703724 - tokio::runtime::coop::with_budget::h4bad6ffc6dec5ba7
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:107:5
  63:     0x55fdbe703724 - tokio::runtime::coop::budget::h87083c2691c386f5
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:73:5
  64:     0x55fdbe703724 - tokio::runtime::park::CachedParkThread::block_on::hb2d2e431ff136be3
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/park.rs:282:31
  65:     0x55fdbe788295 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h83c5635027fcacc0
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/blocking.rs:66:9
  66:     0x55fdbe6cde26 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h1d48993d3bb22f7c
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  67:     0x55fdbe702584 - tokio::runtime::context::runtime::enter_runtime::hbd2c0fe5c1895474
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/runtime.rs:65:16
  68:     0x55fdbe6cdde1 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h45300dfcfc521a14
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  69:     0x55fdbe78659e - tokio::runtime::runtime::Runtime::block_on::h6dc55fccae245a6f
                               at /home/dfeyer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/runtime.rs:350:45
  70:     0x55fdbe7c9f33 - ui_api::main::hd6638bd38695d00f
                               at /home/dfeyer/Projects/src/gitlab.ttree.ch/dfeyer/DialogHarvest/ui-api/src/main.rs:48:5
  71:     0x55fdbe7f170b - core::ops::function::FnOnce::call_once::hfe41b4e0f1780bbd
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/ops/function.rs:250:5
  72:     0x55fdbe7c8fde - std::sys_common::backtrace::__rust_begin_short_backtrace::hfcb0955ba3ac7133
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/sys_common/backtrace.rs:154:18
  73:     0x55fdbe654411 - std::rt::lang_start::{{closure}}::h89c1b167559e660e
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/rt.rs:167:18
  74:     0x55fdbf541307 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2e10d4c4ba919a93
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/core/src/ops/function.rs:284:13
  75:     0x55fdbf541307 - std::panicking::try::do_call::hcd9d9a03ab00ff87
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:504:40
  76:     0x55fdbf541307 - std::panicking::try::h0fefef429810ffc6
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:468:19
  77:     0x55fdbf541307 - std::panic::catch_unwind::h86b5298dbe0939be
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panic.rs:142:14
  78:     0x55fdbf541307 - std::rt::lang_start_internal::{{closure}}::h37295094de539c87
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/rt.rs:148:48
  79:     0x55fdbf541307 - std::panicking::try::do_call::ha37dc11bceb0bbca
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:504:40
  80:     0x55fdbf541307 - std::panicking::try::h61664fdf36021c16
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panicking.rs:468:19
  81:     0x55fdbf541307 - std::panic::catch_unwind::h3778000941814f3f
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/panic.rs:142:14
  82:     0x55fdbf541307 - std::rt::lang_start_internal::h796fc901eb42428a
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/rt.rs:148:20
  83:     0x55fdbe6543ea - std::rt::lang_start::h496599e17581540e
                               at /rustc/1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07/library/std/src/rt.rs:166:17
  84:     0x55fdbe7c9fee - main
  85:     0x7f0a1d9c368e - <unknown>
  86:     0x7f0a1d9c3749 - __libc_start_main
  87:     0x55fdbe6223f5 - _start
                               at /home/build/YPKG/root/glibc/build/glibc.git/csu/../sysdeps/x86_64/start.S:115
  88:                0x0 - <unknown>
```

Kind of new to leptos, so something in maybe wrong on my side, I follow the `axum_starter_workspace`, and here is my`lib.rs` for the App:

```
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

pub mod error_template;

mod components;
mod screen;

#[component]
pub fn App() -> impl IntoView {
    // let formatter = |text| format!("{text} - Dialog Harvest AI");
    provide_meta_context();
    view! {
        <Html lang="en"/>
        // <Title formatter/>
        <Meta
            name="description"
            content="Leptos is a cutting-edge Rust web framework designed for building fast, reliable, web applications."
        />
        <div id="root">
            <Router>
                <nav>
                        <A href="" class=move || "my-class">"Home"</A>
                        <A href="harvesting" class=move || "my-class">"Harvesting"</A>
                        <A href="profile" class=move || "my-class">"Profile"</A>
                        <A href="about" class=move || "my-class">"About"</A>
                </nav>
                <main>
                        <Routes>
                            <Route path="" view=screen::home_page::HomePage/>
                            <Route path="harvesting" view=screen::harvesting::Harvesting/>
                            <Route path="profile" view=screen::profile::Profile/>
                            <Route path="about" view=screen::about::About/>
                        </Routes>
                </main>
            </Router>
        </div>
        <script defer data-domain="dialogharvest.ai" src="https://plausible.io/js/script.js"></script>
    }
}

```

**Leptos Dependencies**

```toml
leptos = { version = "0.5.2", features = ["nightly"] }
leptos_axum = { version = "0.5.2" }
leptos_meta = { version = "0.5.2", features = ["nightly"] }
leptos_router = { version = "0.5.2", features = ["nightly"] }
```

**Expected behavior**
Should see the page title, meta or stylesheet added to the document.

**Comment by dfeyer** [comment]
If I disable the `generate_route_list(App)` from my server API, the app did not panik (cargo leptos watch). So maybe a parsing issue ?

**Comment by gbj** [comment]
This sounds to me like you might have the `csr` or `hydrate` feature enabled on `leptos_meta` while running the server. Can you show the full `Cargo.toml`?

**Comment by dfeyer** [comment]
If I create a simple component with just the router, the parsing is OK.

```

[dependencies]
platy_ui = { path = "../platy-ui" }
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "dep:leptos_axum"]
```

This is the Cargo.toml from the app crate

**Comment by dfeyer** [comment]
Comes from here: https://github.com/leptos-rs/start-axum-workspace/blob/main/app/Cargo.toml

**Comment by gbj** [comment]
These two lines of the backtrace
```
  36:     0x55fdbeef78ce - leptos_dom::document::h44c750b35a8954d5
                               at ...leptos_dom-0.5.2/src/lib.rs:999:5
  37:     0x55fdbeb76d1d - leptos_meta::MetaTagsContext::register::h356a3fdd3dc60ab0
                               at ...leptos_meta-0.5.2/src/lib.rs:139:42
```
Come from line 139 here
https://github.com/leptos-rs/leptos/blob/ad290f5ed2dedd0e0f626586bb41cecd883e2683/meta/src/lib.rs#L135-L140

This is cfg-gated to only run if the `csr` or `hydrate` features are set on `leptos_meta`.

If I run 
```bash
cargo leptos new --git https://github.com/leptos-rs/start-axum-workspace
cd {test directory}
```
add the same `<Meta/>` tag to main component, and then run
```bash
cargo leptos watch
```
I cannot reproduce the issue, i.e., the server starts up correctly and renders the page as expected, without panicking.

What command are you using to run the app?

<img width="1177" alt="Screenshot 2023-10-26 at 6 10 37 PM" src="https://github.com/leptos-rs/leptos/assets/286622/d1c216bf-0b23-4b7f-b5ff-08cbe01850b3">

**Comment by dfeyer** [comment]
Yes I see that also ... so the problem is related to how I did the configuration of my repo.

It's kind of confusing how thing are configured accross all the Cargo.yaml (workspace root and every involved crates). I will continue to investigate, what wrong on my side.

**Comment by dfeyer** [comment]
> This is cfg-gated to only run if the `csr` or `hydrate` features are set on `leptos_meta`.

In the start axum repos, where it the crs feature enabled ? From the snippet i post earlier, right ?

**Comment by dfeyer** [comment]
Something is wrong with one of my crate, who share some basic UI building block in the project ... removing this deps ... remove the panic, so I think we can close this issue, I have a few stuff to learn ;)

Thanks for your help
