### ISSUE TITLE
Actix server function panics with missing `HttpContext`

### ISSUE THREAD

**Issue by ImTheSquid** [leptos-rs/leptos#2132]
**Describe the bug**
This specific server function in my code results in a panic whenever I try to load the associated component:
```rust
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct TermInfo {
    id: String,
    name: String,
    /// You can only delete terms that don't have any associated courses
    can_delete: bool,
}

#[server(GetTerms)]
async fn get_terms() -> Result<Vec<TermInfo>, ServerFnError> {
    use leptos_actix::{extract, ResponseOptions};
    use actix_web::web::Data;
    use crate::server::WebState;
    use goldleaf::{AutoCollection, CollectionIdentity};
    use db::models::{Term, Course};
    use mongodb::bson::{doc, oid::ObjectId, from_document};
    use crate::AuthedUser;

    extract(move |data: Data<WebState>, _user: AuthedUser<{db::Role::Admin}>| async move {
        let stage_attach_num_associated = doc! {
            "$lookup": {
                "from": Course::COLLECTION,
                "localField": "_id",
                "foreignField": "term",
                "as": "associated_courses",
            }
        };

        let stage_set_can_delete = doc! {
            "$setField": {
                "can_delete": {
                    "$cond": {
                        "if": {
                            "$gt": [
                                {"$size": "$associated_courses"},
                                0,
                            ]
                        }
                    }
                }
            }
        };

        let terms = data.database.auto_collection::<Term>().aggregate(vec! [
            doc! {
                "$sort": {
                    "_id": -1,
                }, 
            },
            stage_attach_num_associated,
            stage_set_can_delete,
        ], None).await?.try_collect::<Vec<_>>().await?;

        let terms = terms.into_iter().map(from_document).try_collect::<Vec<Term>>()?.into_iter().map(|t| {
            TermInfo {
                id: t.id.unwrap().to_hex(),
                name: t.name,
                can_delete: t.can_delete.unwrap(),
            }
        }).collect::<Vec<_>>();

        Ok(terms)
    }).await?
}

#[component]
pub fn Courses() -> impl IntoView {
    let terms = create_blocking_resource(|| (), |_| async move { get_terms().await });

    let manage_terms_ref = create_node_ref::<Dialog>();

    view! {
        <div>
            <h2>"Course and Term Configuration"</h2>
            <button on:click=move |_| manage_terms_ref.get().unwrap().show_modal().expect("Failed to show Term modal!")>"Manage Terms..."</button>
        </div>
        <dialog node_ref=manage_terms_ref>
            <h1>"Manage Terms"</h1>
        </dialog>
    }
}
```

```rust
thread 'actix-rt|system:0|arbiter:3' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_actix-0.5.4/src/lib.rs:1409:10:
HttpRequest should have been provided via context
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3d0e6bed600c0175628e96f1118293cf44fb97bd/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/3d0e6bed600c0175628e96f1118293cf44fb97bd/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/3d0e6bed600c0175628e96f1118293cf44fb97bd/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/3d0e6bed600c0175628e96f1118293cf44fb97bd/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/3d0e6bed600c0175628e96f1118293cf44fb97bd/library/core/src/option.rs:1980:5
   5: web::admin::__Courses::{{closure}}::{{closure}}
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::task::local::LocalSet::tick
   9: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
  11: tokio::runtime::scheduler::current_thread::Context::enter
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  14: tokio::runtime::context::runtime::enter_runtime
  15: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have other server functions with extractors defined in the same module invoked in the same way that work without any issues. I cleared my cache on the browser and tried multiple different browsers, but they all have the same issue. I've tracked the issue to [here](https://github.com/leptos-rs/leptos/blob/9f4c480725195d32fff8ff13a047418b463b9b98/integrations/actix/src/lib.rs#L1431), but I do call the necessary registration functions in my `main`, so I don't know why this is happening.

**Leptos Dependencies**
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_actix = { version = "0.5", optional = true }
leptos_router = { version = "0.5", features = ["nightly"] }
```

Cargo has picked 0.5.4 for building, but above is the exact contents of my TOML file.

**To Reproduce**
1. Create a server function with an Actix backend
2. Call it from a component

**Expected behavior**
The server function runs without any issues (at least related to extractors).

**Additional context**
The commit with the offending code is here: https://github.com/ImTheSquid/CodeCheck/commit/289e8853261a8fc22aa3a6bb1b5b859bf9639fe8

This is in `web/src/admin.rs` near the bottom.

**Comment by ImTheSquid** [comment]
I did some more experimenting, and discovered that the problem seems to lie in the route definitions. Specifically, I have a component for checking if the user is logged in that wraps protected routes:
```rust
#[server(ValidateLogin)]
async fn validate_login(required_role: Role) -> Result<ValidatedUser, ServerFnError> {
    use leptos_actix::{extract, ResponseOptions};
    use actix_web::HttpRequest;
    use actix_web::web::Data;
    use crate::server::WebState;

    let response = expect_context::<ResponseOptions>();
 
    extract(move |data: Data<WebState>, req: HttpRequest| async move {
        let cookie = match req.cookie("session") {
            None => {
                leptos_actix::redirect(&format!("/login?next={}", urlencoding::encode(req.path())));
                return Err(ServerFnError::ServerError("No cookie present!".to_string()));
            },
            Some(cookie) => cookie,
        };

        let res = match auth::validate_token(&data.database, cookie.value()).await.map_err(|e| ServerFnError::ServerError(e.to_string())) {
            Err(e) => {
                leptos_actix::redirect(&format!("/login?next={}", urlencoding::encode(req.path())));
                return Err(ServerFnError::ServerError(e.to_string()));
            },
            Ok(res) => res,
        };
        
        if res.role < required_role {
            response.set_status(actix_web::http::StatusCode::FORBIDDEN);
            return Err(ServerFnError::ServerError("Forbidden".to_string()));
        }

        Ok(res)
    }).await?
}

/// Requires the user to be logged in to see the inner view, otherwise
/// redirects user to log in page.
#[component]
pub fn LoggedIn(#[prop(optional)] required_role: Option<Role>, children: ChildrenFn) -> impl IntoView {
    // Default to requiring Admin rights to see a view, makes sure I don't
    // mess up and expose something I shouldn't through negligence
    let required_role = required_role.unwrap_or(Role::Admin);

    let logged_in = create_blocking_resource(move || required_role, |role| async move {  
        validate_login(role).await
    });

    let children = store_value(children);

    view! {
        <Transition fallback=move || view! { <p>"Validating session data..."</p> }>
            {move || {
                if let Some(li) = logged_in.get() {
                    match li {
                        Ok(li) => {
                            provide_context(li);
                            children().into_view()
                        },
                        Err(e) => {
                            view! {
                                <p style="color: red;">{e.to_string()}</p>
                            }.into_view()
                        }
                    }
                } else {
                    ().into_view()
                }
                
            }}
        </Transition>
    }
}
```

Used like this:
```rust
<Route path="admin" view=|| view! {
                        <LoggedIn>
                            <Outlet/>
                        </LoggedIn>
                    }>
                        <Route path="users" view=admin::Users/>
                        <Route path="courses" view=admin::Courses/>
                    </Route>
```

However, for some reason this causes some routes to panic, seemingly at random. `admin/users` works, but `admin/courses` panics, even when both routes use the exact same code. Removing the `LoggedIn` wrapper fixes the issue, but is not workable since it removes functionality. Is it possible that extracting the `HttpRequest` structure in the validation code causes this issue?

I also tried just ignoring the panic using the `extract!` macro, and while the panic message still shows, the function still executes in its entirety, including the parts where it shouldn't, so maybe it's running twice?

**Comment by gbj** [comment]
Sorry, I don't have a way to reproduce this, because I can't run your actual app without the DB. I cloned the `interface` branch of your repo and spent some time trying to remove the parts that would be necessary to remove (stubbing out the database, etc.) but can't get the panic. If you can create a reproducible example I'd be happy to explore it and see if I can figure out the issue.

**Comment by ImTheSquid** [comment]
For some reason the issue just disappeared after adding more components, so I'll close this and reopen it if I get more issues/concrete evidence.
