### ISSUE TITLE
`0.7-beta` Panic when trying to render nested `island` 

### ISSUE THREAD

**Issue by boyswan** [leptos-rs/leptos#2724]
Trying to render an island panics when trying to render primitive types

```rust
#[island]
fn Panic1() -> impl IntoView {
    view! { <div>Hello</div> }
}

#[island]
fn Panic2() -> impl IntoView {
    view! { "Hello" }
}

#[island]
fn Panic3() -> impl IntoView {
    view! { <div><span>{0.0}</span></div> }
}

#[island]
fn NoPanic() -> impl IntoView {
    view! { <div></div> }
}

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();
    view! {
      <Router>
        <Routes fallback=|| "This page could not be found.">
          <Route path=path!("test") view=Panic1/>
        </Routes>
      </Router>
    }
}
```

The panic message for rendering a string is:

```
test.js:483 panicked at /Users/.../.cargo/git/checkouts/leptos-2c8932a5258b3db6/2abb56a/tachys/src/view/strings.rs:97:14:
couldn't cast text node from node
```

And for rendering (in this case) a float:
```
test.js:490 panicked at  /Users/.../.cargo/git/checkouts/leptos-2c8932a5258b3db6/2abb56a/tachys/src/view/primitives.rs:139:1:
couldn't cast text node from node
```

**Comment by gbj** [comment]
Hm, I can't reproduce this: if I open the `islands` example, copy and paste the code above, and go to `/test`, I do not get a panic.

**Comment by boyswan** [comment]
Ahh sorry my bad, I just realised I had `leptos::mount::hydrate_body(App)` instead of `leptos::mount::hydrate_islands();`.

Working as expected with the correct hydrate method!

**Comment by boyswan** [comment]
I've managed to trigger the same panic with the following:

```rust
#[island]
fn Inner() -> impl IntoView {
    view! { <div>Hello</div> }
}

#[island]
fn Example() -> impl IntoView {
    view! {
      <div>
        <Inner/>
      </div>
    }
}
```

Will reopen and rename the issue

**Comment by gbj** [comment]
Thanks! 1bc8854 should update the hydration walk correctly — at least it stands up to this fairly complex island interweaving example mixing together the others in this issue so far, as well as `children`. 

Keep them coming, looks like you're testing out islands more thoroughly than I have so far, so let me know what else is wrong.

```rust

#[component]
pub fn App() -> impl IntoView {
    view! {
        <div>
            <Inner/>
            <span>"Test"</span>
            "Foo"
            <Example/>
            <Panic1/>
            <Panic2>
                <Panic3/>
            </Panic2>
        </div>
    }
}

#[island]
fn Inner() -> impl IntoView {
    view! { <div>Hello</div> }
}

#[island]
fn Example() -> impl IntoView {
    view! {
        <div>
            <Inner/>
        </div>
    }
}

#[island]
fn Panic1() -> impl IntoView {
    view! { <div>Hello</div> }
}

#[island]
fn Panic2(children: Children) -> impl IntoView {
    ("Hello", children())
}

#[island]
fn Panic3() -> impl IntoView {
    view! {
        <div>
            <span>{0.0}</span>
        </div>
    }
}

#[island]
fn NoPanic() -> impl IntoView {
    view! { <div></div> }
}
```
