### ISSUE TITLE
Panic with Effect inside nested Suspense in outsite component (tested on `0.7-beta`)

### ISSUE THREAD

**Issue by osmano807** [leptos-rs/leptos#2754]
**Describe the bug**
Getting a panic when creating an Effect in nested Suspense components. When commenting the Effect or any of the Suspenses, no panic.

```rust
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{
    components::*,
    StaticSegment,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html> 
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <AutoReload options=options.clone() />
                <HydrationScripts options />
                <MetaTags />
            </head>
            <body>
                <App />
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/start_axum.css" />

        // sets the document title
        <Title text="Welcome to Leptos" />

        // content for this welcome page

        <Router>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>                    
                    <Route path=StaticSegment("") view=HomePage />
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn HomePage() -> impl IntoView {
    view! {
        <Suspense>
            <OuterPage />
        </Suspense>
    }
}

#[component]
fn InnerPage() -> impl IntoView {

    Effect::new(|_| { });

    view! { <h1>"Welcome to Inner!"</h1> }
}

#[component]
fn OuterPage(
) -> impl IntoView {

    view! {
        <Suspense>
            <InnerPage />
        </Suspense>
    }
}
```

I'm getting the following panic:
```
thread 'tokio-runtime-worker' panicked at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1:
Dropped SendWrapper<T> variable from a thread different to the one it has been created with.
```

<details>
  <summary>Click to see the backtrace</summary>

```rust
thread 'tokio-runtime-worker' panicked at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1:
Dropped SendWrapper<T> variable from a thread different to the one it has been created with.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panicking.rs:264:5
   3: send_wrapper::invalid_drop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/send_wrapper-0.6.0/src/lib.rs:291:3
   4: <send_wrapper::SendWrapper<T> as core::ops::drop::Drop>::drop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/send_wrapper-0.6.0/src/lib.rs:230:4
   5: core::ptr::drop_in_place<send_wrapper::SendWrapper<core::option::Option<alloc::sync::Arc<std::sync::rwlock::RwLock<reactive_graph::effect::inner::EffectInner>>>>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
   6: core::ptr::drop_in_place<alloc::boxed::Box<dyn core::any::Any+core::marker::Send+core::marker::Sync>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
   7: core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn core::any::Any+core::marker::Send+core::marker::Sync>>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
   8: <std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner> as reactive_graph::owner::Cleanup>::cleanup::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner.rs:360:42
   9: reactive_graph::owner::arena::Arena::with_mut::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner/arena.rs:74:17
  10: std::thread::local::LocalKey<core::cell::RefCell<T>>::with_borrow::{{closure}}
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:471:26
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:283:12
  12: std::thread::local::LocalKey<T>::with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:260:9
  13: std::thread::local::LocalKey<core::cell::RefCell<T>>::with_borrow
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:471:14
  14: reactive_graph::owner::arena::Arena::with_mut
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner/arena.rs:73:13
  15: <std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner> as reactive_graph::owner::Cleanup>::cleanup
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner.rs:358:13
  16: <std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner> as reactive_graph::owner::Cleanup>::cleanup
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner.rs:350:17
  17: <std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner> as reactive_graph::owner::Cleanup>::cleanup
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner.rs:350:17
  18: <reactive_graph::owner::OwnerInner as core::ops::drop::Drop>::drop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner.rs:315:17
  19: core::ptr::drop_in_place<reactive_graph::owner::OwnerInner>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
  20: core::ptr::drop_in_place<core::cell::UnsafeCell<reactive_graph::owner::OwnerInner>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
  21: core::ptr::drop_in_place<std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
  22: alloc::sync::Arc<T,A>::drop_slow
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/alloc/src/sync.rs:1839:18
  23: <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/alloc/src/sync.rs:2526:13
  24: core::ptr::drop_in_place<alloc::sync::Arc<std::sync::rwlock::RwLock<reactive_graph::owner::OwnerInner>>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
  25: core::ptr::drop_in_place<reactive_graph::owner::Owner>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
  26: core::mem::drop
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/mem/mod.rs:941:24
  27: leptos_integration_utils::ExtendResponse::from_app::{{closure}}::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_integration_utils-0.7.0-beta/src/lib.rs:61:25
  28: <futures_util::stream::once::Once<Fut> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/once.rs:46:33
  29: <futures_util::stream::stream::chain::Chain<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/chain.rs:56:9
  30: <reactive_graph::owner::arena::sandboxed::Sandboxed<T> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta/src/owner/arena.rs:170:23
  31: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26
  32: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:196:9
  33: <axum_core::body::StreamBody<S> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/body.rs:205:36
  34: <http_body_util::combinators::map_err::MapErr<B,F> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-body-util-0.1.2/src/combinators/map_err.rs:62:15
  35: <http_body_util::combinators::box_body::UnsyncBoxBody<D,E> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-body-util-0.1.2/src/combinators/box_body.rs:103:9
  36: <axum_core::body::Body as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/body.rs:122:9
  37: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:373:39
  38: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:173:21
  39: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:149:16
  40: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:128:28
  41: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:471:9
  42: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/server/conn/http1.rs:511:26
  43: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.6/src/server/conn/auto.rs:593:28
  44: <axum::serve::Serve<M,S> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.5/src/serve.rs:218:26
  45: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
  46: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
  47: tokio::runtime::task::core::Core<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
  48: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
  49: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panic/unwind_safe.rs:272:9
  50: std::panicking::try::do_call
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:554:40
  51: __rust_try
  52: std::panicking::try
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:518:19
  53: std::panic::catch_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panic.rs:345:14
  54: tokio::runtime::task::harness::poll_future
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
  55: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
  56: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
  57: tokio::runtime::task::raw::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
  58: tokio::runtime::task::raw::RawTask::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
  59: tokio::runtime::task::LocalNotified<S>::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:427:9
  60: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:594:13
  61: tokio::runtime::coop::with_budget
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  62: tokio::runtime::coop::budget
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  63: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:593:9
  64: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:556:24
  65: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:509:21
  66: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
  67: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:26
  68: std::thread::local::LocalKey<T>::try_with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:283:12
  69: std::thread::local::LocalKey<T>::with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:260:9
  70: tokio::runtime::context::set_scheduler
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
  71: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:504:9
  72: tokio::runtime::context::runtime::enter_runtime
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  73: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:496:5
  74: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:462:45
  75: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/task.rs:42:21
  76: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
  77: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
  78: tokio::runtime::task::core::Core<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
  79: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
  80: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panic/unwind_safe.rs:272:9
  81: std::panicking::try::do_call
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:554:40
  82: __rust_try
  83: std::panicking::try
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:518:19
  84: std::panic::catch_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panic.rs:345:14
  85: tokio::runtime::task::harness::poll_future
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
  86: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
  87: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
  88: tokio::runtime::task::raw::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
  89: tokio::runtime::task::raw::RawTask::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
  90: tokio::runtime::task::UnownedTask<S>::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:464:9
  91: tokio::runtime::blocking::pool::Task::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:160:9
  92: tokio::runtime::blocking::pool::Inner::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:518:17
  93: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:476:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Leptos Dependencies**
```toml
leptos = { version = "0.7.0-beta", features = ["nightly"]}
leptos_axum = { version = "0.7.0-beta", optional = true }
leptos_meta = { version = "0.7.0-beta" }
leptos_router = { version = "0.7.0-beta", features = ["nightly"]}
```

**To Reproduce**
1. `cargo leptos serve` the code
2. Run multiple connections to the endpoint, for example:
```
wrk -t2 -c4 -d30s http://localhost:9000/
```
3. See the panic

**Expected behavior**
No panics on the server

**Additional context**
Also tried directly with the commit 29b117bdcabf2c81a2e62eaab0ea3b94a6a99ce3 of `leptos_0.7`, still panics. Didn't try with 0.6.

**Comment by gbj** [comment]
I'm pretty sure I understand why this is happening and it makes sense to me, but I was unable to reproduce it. Could you test whether b05581c resolves the issue?

**Comment by osmano807** [comment]
No panics using the provided reproduction example using 5ad17d6.
Still getting the same `SendWrapper` panic in my application, I guess I need to isolate further the issue. If I reproduce it I'll create a new issue.
