### ISSUE TITLE
Panic with closure and callbacks in nested Suspense

### ISSUE THREAD

**Issue by osmano807** [leptos-rs/leptos#2756]
**Describe the bug**
Getting a panic when trying to use a closure inside an `on:input` callback, while in a nested `Suspense`. If I remove any of the suspenses, no panic. Maybe related to #2754 .

```rust
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{
    components::*,
    StaticSegment,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html> 
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <AutoReload options=options.clone() />
                <HydrationScripts options />
                <MetaTags />
            </head>
            <body>
                <App />
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/start_axum.css" />

        // sets the document title
        <Title text="Welcome to Leptos" />

        // content for this welcome page

        <Router>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("") view=HomePage />
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn HomePage() -> impl IntoView {
    view! {
        <Suspense>
            <OuterPage />
        </Suspense>
    }
}

#[component]
fn InnerPage() -> impl IntoView {

    let debounced_fn = move || {};

    view! {
        <Form
            action=""
            on:input=move |_| {
                debounced_fn();
            }
        >
            <input type="text" />
        </Form>
    }
}

#[component]
fn OuterPage(
) -> impl IntoView {

    view! {
        <Suspense>
            <InnerPage />
        </Suspense>
    }
}
```

I'm getting the following panic:
```
thread 'tokio-runtime-worker' panicked at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1:
Dropped SendWrapper<T> variable from a thread different to the one it has been created with.
```

<details>
  <summary>Click to see the backtrace</summary>

```rust
thread 'tokio-runtime-worker' panicked at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1:
Dropped SendWrapper<T> variable from a thread different to the one it has been created with.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panicking.rs:264:5
   3: send_wrapper::invalid_drop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/send_wrapper-0.6.0/src/lib.rs:291:3
   4: <send_wrapper::SendWrapper<T> as core::ops::drop::Drop>::drop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/send_wrapper-0.6.0/src/lib.rs:230:4
   5: core::ptr::drop_in_place<send_wrapper::SendWrapper<leptos_router::form::__Form::inner::{{closure}}>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
   6: core::ptr::drop_in_place<tachys::html::event::On<tachys::html::event::submit,leptos_router::form::__Form::inner::{{closure}},tachys::renderer::dom::Dom>>
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/ptr/mod.rs:536:1
   7: <tachys::html::event::On<E,F,R> as tachys::html::attribute::Attribute<R>>::to_html
             at /home/opc/Documents/leptos/tachys/src/html/event.rs:244:5
   8: <(A,B,C,D,E) as tachys::html::attribute::Attribute<Rndr>>::to_html
             at /home/opc/Documents/leptos/tachys/src/html/attribute/mod.rs:280:8
   9: tachys::html::element::attributes_to_html
             at /home/opc/Documents/leptos/tachys/src/html/element/mod.rs:410:5
  10: <tachys::html::element::HtmlElement<E,At,Ch,Rndr> as tachys::view::RenderHtml<Rndr>>::to_html_async_with_buf
             at /home/opc/Documents/leptos/tachys/src/html/element/mod.rs:319:26
  11: <tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::to_html_async_with_buf::{{closure}}
             at /home/opc/Documents/leptos/tachys/src/reactive_graph/owned.rs:144:13
  12: reactive_graph::owner::Owner::with
             at /home/opc/Documents/leptos/reactive_graph/src/owner.rs:190:19
  13: <tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::to_html_async_with_buf
             at /home/opc/Documents/leptos/tachys/src/reactive_graph/owned.rs:143:9
  14: tachys::ssr::StreamBuilder::push_async_out_of_order::{{closure}}
             at /home/opc/Documents/leptos/tachys/src/ssr/mod.rs:191:21
  15: <tachys::ssr::StreamBuilder as futures_core::stream::Stream>::poll_next
             at /home/opc/Documents/leptos/tachys/src/ssr/mod.rs:327:31
  16: <futures_util::stream::stream::chain::Chain<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/chain.rs:50:40
  17: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  18: <futures_util::stream::stream::fuse::Fuse<S> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/fuse.rs:53:27
  19: <futures_util::stream::stream::ready_chunks::ReadyChunks<St> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/ready_chunks.rs:40:19
  20: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26
  21: <futures_util::stream::stream::chain::Chain<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/chain.rs:56:9
  22: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  23: <futures_util::stream::stream::chain::Chain<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/chain.rs:56:9
  24: <futures_util::stream::stream::chain::Chain<St1,St2> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/chain.rs:50:40
  25: <reactive_graph::owner::arena::sandboxed::Sandboxed<T> as futures_core::stream::Stream>::poll_next
             at /home/opc/Documents/leptos/reactive_graph/src/owner/arena.rs:170:23
  26: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26
  27: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:196:9
  28: <axum_core::body::StreamBody<S> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/body.rs:205:36
  29: <http_body_util::combinators::map_err::MapErr<B,F> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-body-util-0.1.2/src/combinators/map_err.rs:62:15
  30: <http_body_util::combinators::box_body::UnsyncBoxBody<D,E> as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-body-util-0.1.2/src/combinators/box_body.rs:103:9
  31: <axum_core::body::Body as http_body::Body>::poll_frame
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/body.rs:122:9
  32: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:373:39
  33: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:173:21
  34: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:149:16
  35: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:128:28
  36: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/proto/h1/dispatch.rs:471:9
  37: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.4.1/src/server/conn/http1.rs:511:26
  38: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.6/src/server/conn/auto.rs:593:28
  39: <axum::serve::Serve<M,S> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.5/src/serve.rs:218:26
  40: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
  42: tokio::runtime::task::core::Core<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panic/unwind_safe.rs:272:9
  45: std::panicking::try::do_call
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:554:40
  46: __rust_try
  47: std::panicking::try
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:518:19
  48: std::panic::catch_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panic.rs:345:14
  49: tokio::runtime::task::harness::poll_future
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
  50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
  51: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
  52: tokio::runtime::task::raw::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
  53: tokio::runtime::task::raw::RawTask::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
  54: tokio::runtime::task::LocalNotified<S>::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:427:9
  55: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:594:13
  56: tokio::runtime::coop::with_budget
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  57: tokio::runtime::coop::budget
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  58: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:593:9
  59: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:544:24
  60: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:509:21
  61: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
  62: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:26
  63: std::thread::local::LocalKey<T>::try_with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:283:12
  64: std::thread::local::LocalKey<T>::with
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/thread/local.rs:260:9
  65: tokio::runtime::context::set_scheduler
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
  66: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:504:9
  67: tokio::runtime::context::runtime::enter_runtime
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  68: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:496:5
  69: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:462:45
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/task.rs:42:21
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panic/unwind_safe.rs:272:9
  76: std::panicking::try::do_call
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:554:40
  77: __rust_try
  78: std::panicking::try
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:518:19
  79: std::panic::catch_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panic.rs:345:14
  80: tokio::runtime::task::harness::poll_future
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
  83: tokio::runtime::task::raw::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:464:9
  86: tokio::runtime::blocking::pool::Task::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:160:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:518:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/opc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:476:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Leptos Dependencies**
Using 5ad17d6 on a local checkout

For example:
```toml
leptos = { path = "~/leptos", features = ["nightly"] }
leptos_axum = { path = "~/leptos/integrations/axum", optional = true }
leptos_meta = { path = "~/leptos/meta" }
leptos_router = { path = "~/leptos/router", features = ["nightly"] }
```

**To Reproduce**
1. `cargo leptos serve` the code
2. Run multiple connections to the endpoint, for example:
```
wrk -t2 -c4 -d30s http://localhost:9000/
```
3. See the panic

**Expected behavior**
No panics on the server

**Comment by gbj** [comment]
Thanks. Yes, related to #2754 in that my brilliant solution for allowing us to use `SendWrapper` to enable `!Send` values for things that are not used on the server (effects, event callbacks, DOM properties, custom directives, browser API types) had a somewhat nasty flaw.

My reasoning was that we never need to access these things during SSR (e.g., we do not actually event listeners on the server) so the wrapper was fine: even if they were sent to another thread, we would never access them there. Unfortunately I'd forgotten that `Drop` *also* needs to check, so if we construct an event listener, send it to another thread under Suspense, and later drop it, it's still a problem.

00fb8f2 adjusts all these types in the renderer so that Suspense on the server should actually drop them earlier, on the thread they were created on. I'm sure there are weird edge cases that will come up... This is not an ideal solution at all and is solely due to the desire to unlock multithreading on the server, balanced against the fact that `JsValue` is `!Send`, and even though it is not constructed on the server the types are infectious.
